---
- hosts: all

  vars_files:
    - vars/{{ ansible_distribution }}.yml
    - default-config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
      when:
        - ansible_distribution == "MacOSX"
    - role: geerlingguy.mac.homebrew
      when:
        - ansible_distribution == "MacOSX"
      tags: ["homebrew"]
    - role: geerlingguy.mac.mas
      when:
        - mas_installed_apps or mas_installed_app_ids
        - ansible_distribution == "MacOSX"
      tags: ["mas"]
    - role: geerlingguy.mac.dock
      tags: ["dock"]
      when:
        - configure_dock
        - ansible_distribution == "MacOSX"

  tasks:
    - name: "Ensure required directories ({{ item }}) exists"
      file:
        state: directory
        path: "{{ item }}"
      loop: "{{ required_directories }}"

    - name: "Install required {{ ansible_distribution }} Packages"
      import_tasks: "tasks/system_packages.yml"
      when:
        - ansible_distribution == "Ubuntu"
      become: true

    - name: Git Config
      community.general.git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      loop: "{{ git_configs }}"
      tags: ["git"]

    - name: Fonts installation
      include_tasks: "tasks/fonts.yml"
      vars:
        font: "{{ item }}"
      loop: "{{ fonts }}"
      tags: ["fonts"]
      args:
        apply:
          tags:
            - fonts

    - include_tasks: tasks/dotfiles.yml
      tags: ["dotfiles", "zsh", "vim"]
      loop:
        - "generic"
        - "{{ ansible_distribution }}"
      args:
        apply:
          tags: ["dotfiles", "zsh", "vim"]

    - name: Setup ZSH and ohmyzsh
      import_tasks: tasks/zsh.yml
      tags: ["zsh"]

    - name: Setup vim plugins
      block:
        - name: Ensure vundle repository is cloned locally and installed.
          git:
            repo: "https://github.com/VundleVim/Vundle.vim.git"
            dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"
            accept_hostkey: "true"

        - name: Install vim plugins
          shell: "vim +PluginInstall +qall"
          args:
            executable: /bin/bash
      tags: ["vim"]

    - name: Setup iterm2
      import_tasks: tasks/terminal.yml
      when:
        - ansible_distribution == "MacOSX"
      tags: ["iterm"]

    - name: Setup kubectl and kubernetes components
      tags: ["kubectl", "krew"]
      include_tasks: "tasks/krew.yml"
      args:
        apply:
          tags: ["kubectl", "krew"]

    - name: ensure fzf completions are installed.
      shell: $(brew --prefix)/opt/fzf/install
      args:
        creates: "{{ ansible_env.HOME }}/.fzf.zsh"

    - name: Terraform setup
      block:
        - name: Check if Terraform is installed.
          shell: which terraform
          register: which_terraform
        - name: Install terraform versions using tfenv
          shell: |
            tfenv install latest
            tfenv use latest
          when: which_terraform.rc != 0
      tags: ["terraform"]

    - name: Node/NVM setup
      block:
        - name: Check if Node is installed.
          shell: which node
          register: which_node
        - name: Install node versions using nvm
          environment:
            NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
          shell: |
            source $NVM_DIR/nvm.sh
            nvm install node
            nvm use node
          when: which_node.rc != 0
      tags: ["node"]

    - import_tasks: tasks/extra-packages.yml
      tags: ["extra-packages"]
